[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "N", "UP", "PL", "RUF"]
ignore = ["E501"]

# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
python_files = "tests.py"
DJANGO_SETTINGS_MODULE = "fedidevs.settings"
